### PR TITLE
Change ics calls to 0.4 API

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/pyvec/naucse.python.cz/issues/412

@mikicz how does this affect current forks? As long as they don't add times so the calendar ics is not generated, they are fine?

### CODE REVIEW

**Comment by hroncok** [comment]
ad forks: do I get it right that a fork that never changed it's `requirements.txt` file is using an old Docker image over and over again, so it will never get a newer version of ics at all?

**Comment by encukou** [comment]
Reading the documentation, I guess this should build a list of events first, then return `ics.Calendar(events=events)`

**Comment by mikicz** [comment]
Ad forks:

The reuse of old images depends on the following:

1. requirements.txt does not change in the fork
2. the image is not deleted from the registry
3. Arca is not upgraded
4. Python is not upgraded

So if any of these conditions are broken, a new image is built -> a newer ics would be installed.
A new ics version in the current forks would break the iCal calendar in Asteroids and in MicroPython workshop runs.

I recognise that the situation is not ideal, the image reuse is only pushing the problem down the line until a new version of Arca is released or Travis starts using a newer Python patch version. But to be fair, it works like this because the requirements are not frozen and builds in fork are bound to fail just like builds on Travis fail for the main repo.

The situation would be much improved if #276 was fixed...

**Comment by hroncok** [comment]
> The situation would be much improved if #276 was fixed...

Agreed.

**Comment by hroncok** [comment]
Amended as per @encukou's suggestion. it works on both 0.3.1 and 0.4.

**Comment by encukou** [comment]
Thank you!

**Pull request merged**
