### PR TITLE
Kurzy: Add pagination

### PR DESCRIPTION
**Pull request by torsava**

### CODE REVIEW

**Comment by hroncok** [comment]
@mikicz I suppose we broke this. Can you coordinate with @torsava to rebase this?

**Comment by mikicz** [comment]
Yep, I definitely broke this. If @torsava doesn't object I'll merge master into his branch (or a branch in my own repo) and he can rebase it?

**Comment by torsava** [comment]
@mikicz I'm afraid I'm not following: Why shouldn't I just rebase onto master of this repo?

**Comment by hroncok** [comment]
I suppose @mikicz was just trying to be helpful here. If you are OK to reabse by your own, go ahead ;)

**Comment by torsava** [comment]
I've taken a look, and the changes clash significantly, so it would take me time get familiar with the new model. Therefore if @mikicz has time for it, please go ahead.

**Comment by mikicz** [comment]
I've merged master into the branch and pushed it to my fork here: https://github.com/mikicz/naucse.python.cz/tree/pagination

There was a slight issue with tests of forks, so I had to update them.

Let me know if you want to update your branch on your own or if you want me to do it (I don't actually even know if I can).

**Comment by hroncok** [comment]
Maybe just rebase it in your branch and create a new PR?

**Comment by mikicz** [comment]
Ok.

**Comment by hroncok** [comment]
Done in https://github.com/pyvec/naucse.python.cz/pull/391

**Pull request closed without merging**
