### PR TITLE
NumPy: Various updates

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
OK, this have started as a typo fix, and ended up by restarting the entire notebook.

I can later try to produce a nicer diff by emitting the image changes, as I don't believe they are important. However not today. Let me know if I shall.

**Comment by hroncok** [comment]
Nota bene:

  - The example with 49.799999999999997 is now corrected to 49.8 by NumPy (or Python?). I've cheated and edited it back manually.
 - There is a new deprecation warning (*The truth value of an empty array is ambiguous...*). I'Ve manually edited the warning not to include my venv path. Also, it seems like we miss some CSS styles for those.

**Comment by encukou** [comment]
Looks good! Thanks!
FWIW, I diffed using [nbdiff](https://nbdime.readthedocs.io/en/latest/), specifically:

```console
$ nbdiff-web \
    <(git show master:lessons/intro/numpy/index.ipynb) \
    <(git show HEAD:lessons/intro/numpy/index.ipynb)
```

**Comment by encukou** [comment]
The issues you found don't look critical, but could you open issues for them?

**Comment by hroncok** [comment]
https://github.com/pyvec/naucse/issues/27

**Comment by hroncok** [comment]
Thanks for the nbdiff-web tip!

**Pull request merged**
