### PR TITLE
PyKnihovny Brno: Add an extra lesson

### PR DESCRIPTION
**Pull request by encukou**

### CODE REVIEW

**Comment by hroncok** [comment]
Actually:

    Error: Filename extension of 'calendar.ics' (type text/calendar) does not match Content-Type: text/html; charset=utf-8

**Comment by hroncok** [comment]
I cannot either. Fresh venv with `pip install -r test_requirements.txt`.

```
$ pip freeze
ansi2html==1.4.2
arca==0.2.1
arrow==0.4.2
atomicwrites==1.1.5
attrs==18.1.0
backcall==0.1.0
bleach==2.1.3
cached-property==1.4.3
certifi==2018.4.16
chardet==3.0.4
click==6.7
cssutils==1.0.2
decorator==4.3.0
dogpile.cache==0.6.5
elsa==0.1.5
entrypoints==0.2.3
Flask==1.0.2
Frozen-Flask==0.15
ghp-import==0.5.5
gitdb2==2.0.3
GitPython==2.1.10
giturlparse==0.9.1
html5lib==1.0.1
ics==0.4
idna==2.7
ipython==6.4.0
ipython-genutils==0.2.0
itsdangerous==0.24
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
more-itertools==4.2.0
nbconvert==5.3.1
nbformat==4.4.0
pandocfilters==1.4.2
parso==0.3.0
pexpect==4.6.0
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.6.0
py==1.5.4
Pygments==2.2.0
pytest==3.6.2
pytest-env==0.6.2
pytest-mock==1.10.0
python-dateutil==2.7.3
PyYAML==3.12
pyzmq==17.0.0
requests==2.19.1
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.3
testpath==0.3.1
tornado==5.0.2
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
```

**Comment by hroncok** [comment]
Let my try to drop Travis caches.

**Comment by hroncok** [comment]
Reproduced.

**Comment by hroncok** [comment]
I'll apply cc6d387b63446487c2ca64715122ce616d434d26 to archived2017 to see if using the same requirements.txt helps.

**Comment by hroncok** [comment]
OK, I know what's going on! Heuréka.

https://naucse.python.cz/2018/micropython-workshop-ostrava/calendar.ics has a rendering error caused by https://github.com/pyvec/naucse.python.cz/issues/412 not being fixed there.

This should not disturb naucse, so only a error is dispalyed there:

nauce_error

However, that's HTML, so FrozenFlask fails, expecting text/calendar. This is a problem in forks error handling for non-HTML files. cc @mikicz

**Comment by hroncok** [comment]
We need to get https://github.com/frenzymadness/naucse.python.cz/pull/2 fixed. Also it's a good idea to request write permissions to repos that are being added, so we can hotfix problems.

**Comment by hroncok** [comment]
Opened https://github.com/pyvec/naucse.python.cz/issues/424 for the actual bug.

**Comment by encukou** [comment]
Thanks for debugging this!

**Pull request merged**
