### PR TITLE
Stuff from MI-PYT

### PR DESCRIPTION
**Pull request by hroncok**
With history. See https://github.com/cvut/MI-PYT/issues/77

### CODE REVIEW

**Comment by hroncok** [comment]
Will fix the Travis failure.

**Comment by hroncok** [comment]
Fixed.

**Comment by encukou** [comment]
Some commit messages mention short MI-PYT issue/PR numbers (e.g. `#73`). These should be changed to the the full URL (e.g. `https://github.com/cvut/MI-PYT/issues/73`).

**Comment by encukou** [comment]
About the data files: could you either move them to `static/` subdirectories and refer to them with `static` (see e.g. [intro/turtle/static](https://github.com/pyvec/naucse.python.cz/tree/ee9cd692f626269f40815bbf9fa61b2fdd4c2a22/lessons/intro/turtle/static) and [the template](https://github.com/pyvec/naucse.python.cz/blame/ee9cd692f626269f40815bbf9fa61b2fdd4c2a22/lessons/intro/turtle/index.md#L96)), or keep them in the MI-PYT repo for now?

The repo structure is not intended to be stable.

**Comment by hroncok** [comment]
Relevant commit messages changed.

**Comment by hroncok** [comment]
What about ipynb files? Keep as they are until https://github.com/pyvec/naucse.python.cz/issues/50 is fixed?

**Comment by hroncok** [comment]
How do I do link to another lesson?

**Comment by encukou** [comment]
Yes, keep them as they are.

**Comment by hroncok** [comment]
Bad link remaining:

 * Jupyter notebooks (will fix after #50, this can be merged)
 * PyQt pics (leads to non-raw GtiHub with README etc.)

**Comment by encukou** [comment]
Please also apply these:
```patch
diff --git a/lessons/intro/async/index.md b/lessons/intro/async/index.md
index 7a429d6..fa93a9b 100644
--- a/lessons/intro/async/index.md
+++ b/lessons/intro/async/index.md
@@ -5,7 +5,7 @@ Na část toto cvičení bude opět potřeba PyQt5.
 Můžete použít virtualenv z minula, nebo PyQt5 nainstalovat znovu (viz [minulá lekce]).
 (Nejde-li to, nevadí – úplně nezbytné dnes PyQt nebude.)
 
-[minulá lekce]: 09_pyqt.md
+[minulá lekce]: {{ lesson_url('intro/pyqt') }}
 
 Další knihovny pro dnešní den:
 
diff --git a/lessons/intro/pyqt/index.md b/lessons/intro/pyqt/index.md
index baa75c7..9971c3d 100644
--- a/lessons/intro/pyqt/index.md
+++ b/lessons/intro/pyqt/index.md
@@ -118,9 +118,9 @@ Tady jsou některé zvláštnosti, na které se můžete připravit.
 Qt pojmenovává funkce, metody a atributy konvencí `camelCase`, místo pythonistického `snake_case`.
 PyQt tuto konvenci nemění: je užitečnější používat identická jména, a kromě toho knihovna PyQt vznikla ještě před PEP 8.
 
-Hledáte-li dokumentaci, doporučuji zadat do vyhledávače "qt5 <hledaný objekt>".
+Hledáte-li dokumentaci, doporučuji zadat do vyhledávače `qt5 <hledaný objekt>`.
 Dostanete se tak na dokumentaci pro C++ (např. [QObject](http://doc.qt.io/qt-5/qobject.html)).
-Hledáte-li "pyqt5 <hledaný objekt>", dostanete se k dokumentaci pro Python, která ale většinou jen odkazuje
+Hledáte-li `pyqt5 <hledaný objekt>`, dostanete se k dokumentaci pro Python, která ale většinou jen odkazuje
 na verzi pro C++ (např. [pro QObject](http://pyqt.sourceforge.net/Docs/PyQt5/api/qobject.html)).
 
 Rozdíly mezi C a pythonní verzí jsou většinou intuitivní (např. None místo NULL), ale jsou popsány
```

**Comment by hroncok** [comment]
I've missed that one.

**Comment by hroncok** [comment]
Done.

**Pull request merged**
