### PR TITLE
Pin pip and pipenv versions for now

### PR DESCRIPTION
**Pull request by hroncok**
pipenv is broken by:

https://github.com/pypa/pipenv/issues/2956

### CODE REVIEW

**Comment by hroncok** [comment]
This is broken, yet no idea what's going on :(

**Comment by encukou** [comment]
I assume `pipenv install git+https://github.com/pyvec/arca.git@pip_pipenv#egg=arca` overrides Pipfile's `arca = {extras = ["docker"], version = ">= 0.3"}`, so `docker` doesn't get pulled in.

**Comment by hroncok** [comment]
Holy hell. https://github.com/pypa/pipenv/issues/2504

**Comment by hroncok** [comment]
I still see:

```
$ pipenv run naucse list_courses
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
Try "__main__.py --help" for help.
Error: No such command "list_courses".
```

But it does something... let's see if it doesn't render error messages everywhere.

**Comment by encukou** [comment]
I guess this also brings in a newer click, which normalizes `list_courses` to `list-courses`.
So many normalization issues!

**Comment by hroncok** [comment]
I wonder how gets click 7 installed when we explicitly have it pinned in Pipfile.lock, and it's not brought in by install arca or docker.

**Comment by hroncok** [comment]
I've tried to set the click version to `>=7` or `<7` but I fail to generate new Pipfile.lock with weird GitPython related errors. I've had enough. I explicitly set the name fo the command to contain dash, so it now works with both click 6 and 7.

This can now go in. It's an ugly hack, but still a better than having @encukou deploying the site manually every day.

**Comment by encukou** [comment]
Thank you!

**Pull request merged**
