### PR TITLE
Use a cached model when freezing

### PR DESCRIPTION
**Pull request by encukou**
This speeds up freezing by not reading metadata over and over again.

### CODE REVIEW

**Comment by hroncok** [comment]
00:01:17 to 00:00:13 on my machine. Nice.

**Comment by messa** [comment]
These things are much nicer when implemented as decorators ;) See itertools.lru_cache.

**Comment by hroncok** [comment]
d0401d7fff1c90b158c61b76c2c99eb837bb3174

**Comment by hroncok** [comment]
Not sure if non-debug only lru_cache would be nicer, but feel free to propose a change.

**Comment by messa** [comment]
My improvement suggestion using decorators: #210

**Pull request closed without merging**
