### PR TITLE
Archive all 2017 runs

### PR DESCRIPTION
**Pull request by hroncok**
Related to https://github.com/pyvec/naucse.python.cz/issues/419

### CODE REVIEW

**Comment by hroncok** [comment]
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by hroncok** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

Let's wait

**Comment by hroncok** [comment]
Builds now.

**Comment by mikicz** [comment]
There's some weird error while freezing ```/2017/pyladies-brno-jaro-po/sessions/install/```

```UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)```

See the naucse.log ouput for more details.

**Comment by hroncok** [comment]
Right. Could you please check the details? I'm of to the Fedora Release Party.

**Comment by mikicz** [comment]
I'll try!

**Comment by hroncok** [comment]
https://github.com/pyvec/naucse.python.cz/tree/archived2017/runs/2017/pyladies-brno-jaro-po has some custom session cover page

**Comment by mikicz** [comment]
I found the problem, I'll fix it in a PR which will then need to be merged to the `archived2017` branch.

**Pull request merged**
