### PR TITLE
A different approach to model caching

### PR DESCRIPTION
**Pull request by messa**
Using more "functional style" for better code readabilty (hopefully).

What do you think?

### CODE REVIEW

**Comment by hroncok** [comment]
I'd rather do it as `@lru_nodebug_cache` decorator. That decorator would be an if/else for lru_cache or identity. What do you think?

**Comment by hroncok** [comment]
(Because now the benefit of lru_cache being a decorator is gone).

**Comment by encukou** [comment]
I'm not saying the original logic is straightforward, but it's also not complex. I don't see much benefit in replacing it like this. To understand this code the reader needs to know (or read) about `lru_cache` *and* how decorators work (since lru_cache isn't used the normal way). For that matter, I think a `lru_nodebug_cache` would be needlessly complex as well. Not clear enough to get rid of the comment :)
But I also think it's a bit of bikeshedding. If you feel strongly about this, why not merge it.

Although, now that I think about it, I see one flaw in both implementations: the cache shouldn't really be global, but per-app. (Perhaps stored in `app.config`? Don't know where a per-app cache should go in Flask.) That strikes me as a bigger problem – it's not encapsulated & commented, it can surprise future users of the code.

**Comment by messa** [comment]
> I see one flaw in both implementations: the cache shouldn't really be global, but per-app

That's good point. It could be per-app, but even global cache is perfectly OK and correct, as long as the function it wraps doesn't depend on any state other than the input arguments. Well, here it depends on `app.root_path`, but can be fixed easily by explicitly passing model root path to the cached function.

> I'm not saying the original logic is straightforward, but it's also not complex.

I consider the original code not straightforward, but not complex.
I consider my proposed code much more straightforward, but requires knowledge about higher order functions.

But the rest of this project is totally filled with decorators, properties, proxies, class hiearchies and other stuff...

> But I also think it's a bit of bikeshedding.

A little bit :) It's just discussion about how to do things. Every code review could be viewed as bikeshedding (or not? I don't know). 

> Not clear enough to get rid of the comment :)

The comment (docstring) has to be there because of the internal behavior of the model itself; the comment explains why caching should be done. In the original version the comment _also_ explains _how_ the caching is done; that's not necessary in my revised version (I just failed to revise the comment).

**Comment by encukou** [comment]
> > I see one flaw in both implementations: the cache shouldn't really be global, but per-app
> 
> That's good point. It could be per-app, but even global cache is perfectly OK and correct, as long as the function it wraps doesn't depend on any state other than the input arguments. Well, here it depends on `app.root_path`, but can be fixed easily by explicitly passing model root path to the cached function.

It's `config['DEBUG']` as well as `root_path`, so I'd just pass the whole `app` should be passed.

> > I'm not saying the original logic is straightforward, but it's also not complex.
> 
> I consider the original code not straightforward, but not complex.
> I consider my proposed code much more straightforward, but requires knowledge about higher order functions.

I consider higher-order functions (and how decorators are implemented in terms of that) to be more magic than is needed here.

> But the rest of this project is totally filled with decorators, properties, proxies, class hiearchies and other stuff...

True! If you see a way to untangle things, let me know.
(I did try to limit the magic to `modelutils.py` though; `routes.py` is almost entirely simple calls and some registration decorators.) 
Anyway, existing complexity isn't a good reason to add more of it.

> > But I also think it's a bit of bikeshedding.
> 
> A little bit :) It's just discussion about how to do things.

I'm happy to discuss how to do things -- if that's what we're doing here, then sure, let's continue! (And I'm typing all this under that assumption.)

> Every code review could be viewed as bikeshedding (or not? I don't know). 

The word *bikeshedding* is based on a story which [bikeshed.org](http://bikeshed.org/) summarizes as:

> [...] you can go in to the board of directors and
> get approval for building a multi-million or even billion dollar
> atomic power plant, but if you want to build a bike shed you will
> be tangled up in endless discussions.

(Do read the whole thing, though, if you haven't yet!)

The parallel here is that `modelutils.py` is sitting there with hardly anyone commenting on it, yet a self-contained 5-line function gets a redesign, now with three different opinions on how to write it.

Not every review is bikeshedding.
* Adding the cache was, hopefully, useful. (Like building the bikeshed.)
* Replacing the whole thing with a simple decorator from the standard library would -- if you could do it -- be a little improvement. Also, Miro's in-person comments on using `DEBUG` were also useful -- the solution I had in mind before was overengineered. (Like building a bikeshed, rather than an enterprise-grade vehicle storage facility.)
* Suggestions on making naucse's models a bit more approachable would be a worthwhile design discussion. (Like simply swapping two dials on the power plant's control panel to help prevent human error.)
* But trading one kind of complexity in a self-contained function for another kind of complexity is not worth it. (Like painting the shed blue instead of red.)

I don't think the issue here is worth the energy we're spending on it.

> > Not clear enough to get rid of the comment :)
> 
> The comment (docstring) has to be there because of the internal behavior of the model itself; the comment explains why caching should be done. In the original version the comment _also_ explains _how_ the caching is done; that's not necessary in my revised version (I just forgot to revise the comment).

If you really want this PR to go in, it's blocked on revising the comment.

**Comment by hroncok** [comment]
What's the status here? @messa will you revise the comment or shall I close?

**Pull request closed without merging**
