### PR TITLE
Mention alternatives for requests

### PR DESCRIPTION
**Pull request by frenzymadness**
Instead of writing a new lesson about `urllib`, I've decided to just mention the alternatives at the begiining of the lesson about requests.

What do you think?

### CODE REVIEW

**Comment by encukou** [comment]
This much text makes sense a course that introduces the standard library alternatives, but not so much for MI-PYT.
I'd stick to the stdlib's `urllib`: Python 2 is gone; `urllib3` is [not used by much besides Requests](https://urllib3.readthedocs.io/en/latest/#who-uses); `urllib5` is a joke (about a problem that `requests` solves).

I can try to trim the text down, probably next week.

**Comment by encukou** [comment]
How about this?

Finer points:
* AFAIK, "session" is a Requests-specific term, which doesn't make much sense in the intro. For people who know HTTP I wrote "Keep-Alive" instead.
* Requests's docs refer to it as “Requests”, not `requests` or “requests”, so I changed that in the intro and the title.

**Comment by frenzymadness** [comment]
>     * AFAIK, "session" is a Requests-specific term, which doesn't make much sense in the intro. For people who know HTTP I wrote "Keep-Alive" instead.

I don't consider it important or blocking this PR but in my opinion, a session means much more than just Keep-Alive. Keep-Alive is functionality that, when supported by both sides of communication, allows us to keep TCP/IP connection open for more than just one request. On the other hand, session contains much more than just shared low-level connection — auth settings, cookies, … and for me, it's like a real session when you sit in front of a computer and uses a web app for some time.

Feel free to merge it. I think it does what I wanted.

**Comment by encukou** [comment]
> On the other hand, session contains much more than just shared low-level connection — auth settings, cookies, …

True.
In the PR, both cookies and auth are mentioned along with Keep-Alive. I just didn't word the comment well :)

**Review by encukou — APPROVED** [review]

**Pull request merged**
