### PR TITLE
Automatically convert static/.. links to static() call

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/pyvec/naucse.python.cz/issues/93

Introcudes a new "context" dictionary that can be passed to
`convert_markdown()` or `convert_notebook()`.

The conversion only works for Markdown-done images and links,
i.e. it cannot work in HTML documents, calls to other functions
such as `figure(img=static/...)`, or direct HTML in Markdown.

This commit also replaces manual `static()` calls with `static/...`
where possible.

### CODE REVIEW

**Comment by encukou** [comment]
Nice, thanks!
I've thought about this one, and I have some comments on the design.

I thnik `_replace_static_url` in the Markdown renderer is too specific. I can imagine the next step would be replacing `{{subpage_url(xyz)}}` by `./xyz`, or a better syntax for lesson URLs.
Also, a short syntax for internal links doesn't have to be specific to Markdown: I'd expect reST documents to use it as well.
So I think some kind of a `make_url` function, defined by the model, would be better.

As for the context: the problem with passing a dict around is that it's hard to know what should be inside. As more things are put into it, all of its producers and consumers start relying on everything inside, and that leads to unnecessarily tight coupling that's hard to untangle later.
I'd rather see the function passed through its own keyword argument, to explicitly say what needs to be passed where.

Does that make sense, or am I overthinking things?

**Comment by hroncok** [comment]
If we would like to convert all the links, it would probably be easier to do it once we have the resulting HTML, regardless of how it was generated. I.e. put it to (the end of) `Page.render_html()`.

**Comment by encukou** [comment]
I fear that would make naucse unnecessarily slow.

**Comment by hroncok** [comment]
I will make some changes. Got some ideas yesterday.

Dne 13. 4. 2017 10:44 dop. napsal uživatel "Petr Viktorin" <
notifications@github.com>:

**Comment by hroncok** [comment]
Amended. The link conversion logic is in model now. Only a specific thing si passed to the converters, no general "context".

**Comment by encukou** [comment]
Pushed. Thanks!

**Pull request closed without merging**
