### PR TITLE
Convert all cheatsheet links to GitHub pages (opens in webbrowser)

### PR DESCRIPTION
**Pull request by hroncok**
sed -i 's@https://github.com/pyvec/cheatsheets/raw/master/@https://pyvec.github.io/cheatsheets/@g' $(rg -l 'https://github.com/pyvec/cheatsheets/raw/master/')

Fixes https://github.com/pyvec/naucse.python.cz/issues/324

### CODE REVIEW

**Comment by encukou** [comment]
These can all use HTTPS, can't they?
GitHub Pages only has certificate problems on custom domains .

**Comment by hroncok** [comment]
Good point, amended.

**Comment by encukou** [comment]
Thanks for the tip about `rg` :)

**Comment by hroncok** [comment]
https://fedoramagazine.org/oxidizing-fedora-try-rust-applications-today/

**Pull request merged**
