### PR TITLE
Add Brno linux admin course 2024

### PR DESCRIPTION
**Pull request by ejegrova**

### CODE REVIEW

**Comment by ejegrova** [comment]
ptal @encukou @befeleme

**Comment by encukou** [comment]
Looks good but please merge https://github.com/ejegrova/linuxadmin/pull/2 first :)

**Comment by ejegrova** [comment]
> Looks good but please merge [ejegrova/linuxadmin#2](https://github.com/ejegrova/linuxadmin/pull/2) first :)

merged

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
Je to tam! https://naucse.python.cz/2024/brno-linuxadmin-jaro/

**Pull request merged**
